// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.4'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://www.jitpack.io' }
    }
}

// JitPack looks for publishToMavenLocal on the root project. The actual
// publication is defined by the Android library module.
tasks.register('publishToMavenLocal') {
    dependsOn ':artemis_socket_sdk:publishToMavenLocal'
}
